# Конфигурация для dvpl_go
# inputPath: "./input"   # (-i)
# outputPath: "./output" # (-o)
# compressFlag: false    # (-c)
# decompressFlag: false  # (-d)
keepOriginal: false    # (-keep-original)
compress: 1            # (-compress)
# maxWorkers: 2          # (-m)
ignorePatterns:        # (-ignore)
  - "*.exe"
  - "*.dll"
  - "*.pdb"
  - "*.pak"
  # - "temp*"
