# Конфигурация для dvpl_go

# inputPath: "./input"   # (-i)
# outputPath: "./output" # (-o)
# compressFlag: false    # (-c)
# decompressFlag: false  # (-d)
# keepOriginal: false    # (-keep-original)
# forcedCompress: false  # (-forced-compress)
compress: 1            # (-compress)
maxWorkers: 2          # (-m)
ignorePatterns:        # (-ignore)
  - "*.exe"
  - "*.dll"
# ignoreCompress:        # (-ignore-compress)
  # - "*.webp"
